name: Skilled MLflow CI Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train:
    name: Set up job
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check Env
        run: |
          python --version
          pip --version
          echo "Environment OK"

      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=mlruns" >> $GITHUB_ENV

      - name: Run mlflow project
        run: |
          cd Membangun_model
          python modelling_tuning.py

      - name: Install Python dependencies
        run: |
          pip list

      - name: Upload to Google Drive
        run: |
          echo "Simulated upload to Google Drive (skipped)"